"""Canonical Chinese display names for crawlers without SOURCE_NAME."""

CRAWLER_DISPLAY_NAMES = {
    # Central ministries
    "caac_zcfg_crawler.py": "中国民用航空局_政策法规",
    "cac_zcfg_crawler.py": "国家互联网信息办公室_政策法规",
    "cac_zcwj_crawler.py": "国家互联网信息办公室_政策文件",
    "cma_zcfg_crawler.py": "中国气象局_政策法规",
    "cnipa_zcfg_crawler.py": "国家知识产权局_政策法规",
    "court_fabu_crawler.py": "最高人民法院_发布",
    "fire_zfxxgk_crawler.py": "国家消防救援局_政务公开",
    "forestry_zcfg_crawler.py": "国家林业和草原局_政策法规",
    "gov_crawler.py": "中国政府网",
    "gov_interpretation_crawler.py": "中国政府网_政策解读",
    "gov_zcwj_crawler.py": "国务院_政策文件",
    "mct_gfxwj_crawler.py": "文化和旅游部_规范性文件",
    "mct_zwgk_crawler.py": "文化和旅游部_政府信息公开",
    "mee_crawler.py": "生态环境部",
    "mem_tzgg_crawler.py": "应急管理部_通知公告",
    "miit_gzdt_crawler.py": "工业和信息化部_工作动态",
    "miit_tabbox_crawler.py": "工业和信息化部_网站栏目",
    "miit_wjfb_crawler.py": "工业和信息化部_文件发布",
    "miit_wjk_crawler.py": "工业和信息化部_文件库",
    "miit_zcjd_crawler.py": "工业和信息化部_政策解读",
    "mnr_crawler.py": "自然资源部_政策文件",
    "moa_govpublic_crawler.py": "农业农村部_政府信息公开",
    "moe_wj_crawler.py": "教育部_文件",
    "mofcom_ghjh_crawler.py": "商务部_规划计划",
    "mofcom_gztz_crawler.py": "商务部_工作通知",
    "mofcom_zcfb_crawler.py": "商务部_政策发布",
    "mof_crawler.py": "财政部_政策文件",
    "mof_multi_crawler.py": "财政部_多栏目",
    "mohrss_crawler.py": "人力资源和社会保障部_政策文件",
    "mohurd_wjk_crawler.py": "住房和城乡建设部_文件库",
    "most_gfxwj_crawler.py": "科学技术部_规范性文件",
    "most_zjgx_crawler.py": "科学技术部_政策解读",
    "mot_fdzdgk_crawler.py": "交通运输部_政府信息公开",
    "mps_crawler.py": "公安部_政策文件",
    "mva_gfxwj_crawler.py": "退役军人事务部_规范性文件",
    "mwr_gfxwj_crawler.py": "水利部_规范性文件",
    "nda_zwgk_crawler.py": "国家数据局_政务公开",
    "ndcpa_tzgg_crawler.py": "国家疾控局_通知公告",
    "ndcpa_zcfg_crawler.py": "国家疾控局_政策法规",
    "ndrc_crawler.py": "国家发展和改革委员会_政策文件",
    "nea_zxwj_crawler.py": "国家能源局_最新文件",
    "nhsa_col109_crawler.py": "国家医疗保障局_专题栏目",
    "nhsa_zcfg_crawler.py": "国家医疗保障局_政策法规",
    "nmpa_fgwj_crawler.py": "国家药品监督管理局_法规文件",
    "samr_fdzdgk_crawler.py": "国家市场监督管理总局_政府信息公开",
    "sasac_zcfg_crawler.py": "国务院国资委_政策法规",
    "spp_flfh_crawler.py": "最高人民检察院_法律法规",

    # Jiangsu province
    "jiangsu_czt_gg_crawler.py": "江苏省财政厅_公告",
    "jiangsu_czt_zcgg_crawler.py": "江苏省财政厅_政策发布",
    "jiangsu_fzggw_tzgg_crawler.py": "江苏省发展和改革委员会_通知公告",
    "jiangsu_fzggw_zcjd_crawler.py": "江苏省发展和改革委员会_政策解读",
    "jiangsu_fzggw_zcwj_crawler.py": "江苏省发展和改革委员会_政策文件",
    "jiangsu_gat_zcwj_crawler.py": "江苏省公安厅_政策文件",
    "jiangsu_gfdyb_zcwj_crawler.py": "江苏省国防动员办公室_政策文件",
    "jiangsu_gov_gb_crawler.py": "江苏省人民政府_政府公报",
    "jiangsu_gov_zcjd_crawler.py": "江苏省人民政府_政策解读",
    "jiangsu_gov_zxwj_crawler.py": "江苏省人民政府_最新文件",
    "jiangsu_gxt_gsgg_crawler.py": "江苏省工业和信息化厅_公示公告",
    "jiangsu_gxt_wjtz_crawler.py": "江苏省工业和信息化厅_文件通知",
    "jiangsu_gxt_zcwj_crawler.py": "江苏省工业和信息化厅_政策文件",
    "jiangsu_jsgzw_zcwj_crawler.py": "江苏省国资委_政策文件",
    "jiangsu_jshrss_zdgkc_crawler.py": "江苏省人力资源和社会保障厅_重大民生信息",
    "jiangsu_jsip_zcwj_crawler.py": "江苏省知识产权局_政策文件",
    "jiangsu_jswater_zcwj_crawler.py": "江苏省水利厅_规范性文件",
    "jiangsu_mzt_zcwj_crawler.py": "江苏省民政厅_政策文件",
    "jiangsu_mzw_tzgg_crawler.py": "江苏省民族宗教事务委员会_通知公告",
    "jiangsu_scjgj_tzgg_crawler.py": "江苏省市场监督管理局_通知公告",
    "jiangsu_scjgj_zcwj_crawler.py": "江苏省市场监督管理局_政策文件",
    "jiangsu_sjj_gg_crawler.py": "江苏省数据局_通知公告",
    "jiangsu_sjj_zcfb_crawler.py": "江苏省数据局_政策发布",
    "jiangsu_sjj_zcjd_crawler.py": "江苏省数据局_政策解读",
    "jiangsu_sthjt_tzgg_crawler.py": "江苏省生态环境厅_通知公告",
    "jiangsu_styj_zcwj_crawler.py": "江苏省体育局_政策文件",
    "jiangsu_swt_ggtz_crawler.py": "江苏省商务厅_公告通知",
    "jiangsu_swt_yjzj_crawler.py": "江苏省商务厅_意见征集",
    "jiangsu_swt_zcgg_crawler.py": "江苏省商务厅_政策及公告",
    "jiangsu_wjw_zcwj_crawler.py": "江苏省卫生健康委员会_规范性文件",
    "jiangsu_ybj_zcfl_crawler.py": "江苏省医疗保障局_政策法规",
    "jiangsu_yjglt_tzgg_crawler.py": "江苏省应急管理厅_通知公告",
    "jiangsu_zfhcxjst_tf_crawler.py": "江苏省住房和城乡建设厅_通知文件",
}

